development:
  adapter: postgresql
  database: sinai_evaluations_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sinai_evaluations_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sinai_evaluations_production
  pool: 5
  timeout: 5000
